### ISSUE TITLE
你好，拜读了您的项目，有没看懂的地方，望师傅赐教

### ISSUE THREAD

**Issue by CC11001100** [r00t4dm/aLIEz#1]
我是刚刚接触Java内存马，发现了您的项目感觉比较好就拜读了一下，但是有没看懂的地方。

# 一、关于内存马的查杀原理
这个判定是内存马的原理是什么呀？ 
https://github.com/r00t4dm/aLIEz/blob/26368f24d7934a6c0f9cb6095434ed29ce4f2e48/src/main/java/com/r00t4dm/CleanMemShellTransformer.java#L46-L77

# 二、关于恢复
这几个`getDeclaredMethod`方法的原理是什么呢？这几个方法名有什么特殊含义吗？我有点懵懵的...
https://github.com/r00t4dm/aLIEz/blob/26368f24d7934a6c0f9cb6095434ed29ce4f2e48/src/main/java/com/r00t4dm/CleanMemShellTransformer.java#L103
https://github.com/r00t4dm/aLIEz/blob/26368f24d7934a6c0f9cb6095434ed29ce4f2e48/src/main/java/com/r00t4dm/CleanMemShellTransformer.java#L134

感谢带来如此优秀的项目，希望能得到的您的解答。

**Comment by r00t4dm** [comment]
你好，我不得不说这个项目真不算优秀的项目，纯就是自己拿来练手玩的项目，一天就写完的东西。

关于第一个问题：

建议去看一些内存马的原理，你就明白了。
我现在已经不研究内存马了，不知道现在的内存马有没有什么新的技巧，如果还是老三样，我的判定规则应该都是可以发现内存马的。

关于第二个问题：

建议去看一些内存马的具体实现，如冰蝎或哥斯拉，这块纯粹就是敏感词判断，很弱智，如果判定通过，则认为这个文件就是内存马，就会把它“杀掉”。

**Comment by CC11001100** [comment]
谢谢大佬的解答，三年过去了，想学的没有学会，想要的也没有得到，我还是一如既往的菜
